#!/usr/bin/env bash

commit_message=$(<$1)
message_flag="[AUTO-CHECK]"

# check regex match
if ! [[ "$commit_message" =~ "$message_flag" ]]; then   
    exit 0
else 
    echo "$message_flag found, trying to run automated link check"
fi

# Check python3 existance
if command -v python3 &>/dev/null; then
    echo 'Python 3 is installed, Continuing..'	
else
    echo 'Python 3 is not installed'
	echo 'Please install python3 and add to path'
	exit 0
fi

# PATHs
python_script=$PWD/WebChecker/main.py

# Check python script is not exist
if [ ! -f $python_script ]; then
	echo "Automated link check cannot run"
    echo $python_script "not found!"
	exit 0
else
    echo "Running Automated Link Check......"	
fi

# run web checker
# exit message handle by the python script
python3 $python_script
